title: Reaishma N's Portfolio
description: A passionate developer with a keen interest in building innovative projects
url: https://reaishma.github.io
baseurl: /
permalink: /:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

theme: minima
